name: Pipeline Blog

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: advanced_blog_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Générer Prisma
        env: 
            DATABASE_URL: "postgresql://test:test@localhost:5434/advanced_blog_test?schema=public"
        run: npx prisma generate

      - name: Attendre que PostgreSQL soit prêt (sécurité)
        run: |
          for i in {1..20}; do
            nc -z localhost 5434 && echo "DB OK" && break
            echo "DB pas prête... tentative $i"
            sleep 2
          done

      - name: Linter (ESLint)
        run: npm run lint

      - name: Lancer les tests
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5434/advanced_blog_test?schema=public"
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm run test